project:
  type: book
  output-dir: docs

book:
  title: "Semantic Glossary Demo"
  author: "Team OSL"
  date: "7/10/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover/cover.png  



