project:
  type: book
  output-dir: docs

book:
  title: "Semantic Glossary Demo"
  author: "Team OSL"
  date: "2024-07-10"
  chapters:
    - index.qmd
    - cosite001.ipynb
    - ipcc-wip.ipynb
    - epa.ipynb
    - resources/cct.qmd
    - glossaries.qmd
    - references.qmd
    - copy-lic.qmd
  repo-url: https://github.com/TIBHannover/semantic-glosar
  repo-actions: [edit]
  downloads: [pdf,docx,epub]
  cover-image: cover/cover.png 

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    number-sections: false
    theme: cosmo
  pdf:
    number-sections: false
    toc-depth: 1
    documentclass: book
  docx: 
    toc: true
  epub:
    toc: true 


