project:
  type: book
  output-dir: docs

book:
  title: "Semantic Glosar"
  author: "Team Co-Site"
  date: "2024-07-23"
  chapters:
    - index.qmd
    - cosite001.ipynb
    # - ipcc-wip.ipynb
    # - epa.ipynb
    - resources/cct.qmd
    - glossaries.qmd
    - imprint.qmd
    - contributors.qmd 
    - references.qmd
  repo-url: https://github.com/TIBHannover/semantic-glosar
  repo-actions: [edit]
  downloads: [pdf,docx,epub]
  cover-image: cover/cover.png 
  page-footer: 
    center: "[NextGen Books / CPS](https://projects.tib.eu/nextgen-books/)"
    right: "[Impressum](https://projects.tib.eu/nextgen-books/impressum/)"  
    left: "[Datenschutz](https://projects.tib.eu/nextgen-books/datenschutz/)" 

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    number-sections: false
    theme: cosmo
  pdf:
    number-sections: false
    toc-depth: 2
    documentclass: book
    include-in-header: "in-header.tex"
    pagestyle: plain # page numbers
    geometry: # margins
      - top=35mm
      - right=25mm
      - bottom=35mm
      - left=25mm
      - heightrounded
    classoption: openany 
    fontsize: 12pt
    papersize: a4
    urlcolor: cosmoblue
    template-partials:
      - "_titlepage.tex" 
      - "before-body.tex"
    title-bg-image: "cover/cover.png"
    title-bg-location: "" # UL, UR, LR, LL, leave empty for centered
    title-bg-size: 0.50
    title-boxcolor: gray!15!black
    title-boxfontcolor: white

  
  docx: 
    toc: true
  epub:
    toc: true 
    toc-depth: 1
    number-sections: false
    css: cosmoepub.css
    code-overflow: wrap





